apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: dmease/upscale-server:7.0
        volumeMounts:
        - mountPath: /etc/credentials
          name: gcp-credentials
        ports:
        - containerPort: 5000
        env:
          - name: CHUNK_SIZE
            value: "30"
          - name: FLASK_PORT
            value: "5000"
          - name: MONGO_HOST
            value: mongo
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: STORAGE_BUCKET
            value: video_upscale_bucket
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/credentials/gcp-credentials.json
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
          items:
          - key: creds
            path: gcp-credentials.json